/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Equipo;
import Modelo.Impresora;
import Modelo.Pc;
import Modelo.Servidor;
import java.util.ArrayList;

/**
 *
 * @author Juanfran
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        controlador = new Controlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelFormulario = new javax.swing.JLabel();
        jTextFieldCodigoEquipo = new javax.swing.JTextField();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jCheckBoxProtegido = new javax.swing.JCheckBox();
        jButtonAñadirEquipo = new javax.swing.JButton();
        jButtonVerEquipos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldSisOperativo = new javax.swing.JTextField();
        jRadioButtonPc = new javax.swing.JRadioButton();
        jRadioButtonServidor = new javax.swing.JRadioButton();
        jRadioButtonImpresora = new javax.swing.JRadioButton();
        jTextFieldTipoPC = new javax.swing.JTextField();
        jTextFieldYearCompra = new javax.swing.JTextField();
        jTextFieldTipoImpresora = new javax.swing.JTextField();
        jButtonCargarEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelFormulario.setText("Datos Equipo nuevo");

        jTextFieldCodigoEquipo.setText("Codigo de equipo");
        jTextFieldCodigoEquipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoEquipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoEquipoFocusLost(evt);
            }
        });
        jTextFieldCodigoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoEquipoActionPerformed(evt);
            }
        });

        jTextFieldUbicacion.setText("Ubicación");
        jTextFieldUbicacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUbicacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUbicacionFocusLost(evt);
            }
        });

        jTextFieldPrecio.setText("Precio");
        jTextFieldPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecioFocusLost(evt);
            }
        });

        jCheckBoxProtegido.setText("Protegido");

        jButtonAñadirEquipo.setText("Añadir");
        jButtonAñadirEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAñadirEquipoMouseClicked(evt);
            }
        });

        jButtonVerEquipos.setText("Ver Equipos");
        jButtonVerEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerEquiposMouseClicked(evt);
            }
        });
        jButtonVerEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerEquiposActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextFieldSisOperativo.setText("Sistema operativo");
        jTextFieldSisOperativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSisOperativoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSisOperativoFocusLost(evt);
            }
        });
        jTextFieldSisOperativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSisOperativoMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPc);
        jRadioButtonPc.setText("PC");
        jRadioButtonPc.setName("jRadioButtonPc"); // NOI18N
        jRadioButtonPc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonPcMouseClicked(evt);
            }
        });
        jRadioButtonPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPcActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonServidor);
        jRadioButtonServidor.setText("Servidor");
        jRadioButtonServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonServidorMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonImpresora);
        jRadioButtonImpresora.setText("Impresora");
        jRadioButtonImpresora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonImpresoraMouseClicked(evt);
            }
        });

        jTextFieldTipoPC.setText("Tipo PC");
        jTextFieldTipoPC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTipoPCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTipoPCFocusLost(evt);
            }
        });
        jTextFieldTipoPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoPCActionPerformed(evt);
            }
        });

        jTextFieldYearCompra.setText("Año Compra Servidor");
        jTextFieldYearCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldYearCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldYearCompraFocusLost(evt);
            }
        });

        jTextFieldTipoImpresora.setText("Tipo Impresora");
        jTextFieldTipoImpresora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTipoImpresoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTipoImpresoraFocusLost(evt);
            }
        });

        jButtonCargarEquipos.setText("Cargar equipos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonAñadirEquipo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jCheckBoxProtegido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldYearCompra)
                                    .addComponent(jTextFieldTipoPC)
                                    .addComponent(jTextFieldSisOperativo)
                                    .addComponent(jTextFieldTipoImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonPc)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonServidor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonImpresora)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCargarEquipos)
                        .addGap(122, 122, 122)
                        .addComponent(jButtonVerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCargarEquipos))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldCodigoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxProtegido))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonPc)
                                    .addComponent(jRadioButtonServidor)
                                    .addComponent(jRadioButtonImpresora))
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldSisOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jTextFieldTipoImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldTipoPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldYearCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(23, 23, 23)
                        .addComponent(jButtonAñadirEquipo)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAñadirEquipoMouseClicked
        String cod, ubicacion;
        double precio;
        boolean protegido;
        cod = jTextFieldCodigoEquipo.getText();
        ubicacion = jTextFieldUbicacion.getText();
        precio = Double.valueOf(jTextFieldPrecio.getText());
        protegido = jCheckBoxProtegido.isSelected();
        
        
        if (jRadioButtonPc.isSelected()) {
            String ssoo = jTextFieldSisOperativo.getText();
            String tipo = jTextFieldTipoPC.getText();
            
            Pc p = new Pc(ssoo, tipo, cod, ubicacion, precio, protegido);
            controlador.anadirEquipo(p);
        }else if (jRadioButtonServidor.isSelected()) {
            String ssoo = jTextFieldSisOperativo.getText();
            int anoCompra  = Integer.parseInt(jTextFieldTipoPC.getText());
            
            Servidor s = new Servidor(ssoo, anoCompra, cod, ubicacion, precio, protegido);
            controlador.anadirEquipo(s);
        }else if (jRadioButtonImpresora.isSelected()) {
            String tipo = jTextFieldTipoImpresora.getText();
            
            Impresora i = new Impresora(tipo, cod, ubicacion, precio, protegido);
            controlador.anadirEquipo(i);
        }else {
            Equipo e = new Equipo(cod, ubicacion, precio, protegido);
        
            controlador.anadirEquipo(e);
        }
        
        
        
        jTextFieldCodigoEquipo.setText("Codigo Equipo");
        jTextFieldPrecio.setText("Precio");
        jTextFieldUbicacion.setText("Ubicación");
        jTextFieldSisOperativo.setText("Sistema Operativo");
        jTextFieldTipoPC.setText("Tipo PC");
        jTextFieldYearCompra.setText("Año Compra Servidor");
        jTextFieldTipoImpresora.setText("Tipo Impresora");
    }//GEN-LAST:event_jButtonAñadirEquipoMouseClicked

    private void jButtonVerEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerEquiposMouseClicked
        
         jTextArea1.setText(controlador.toString());
        
    }//GEN-LAST:event_jButtonVerEquiposMouseClicked

    private void jTextFieldCodigoEquipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEquipoFocusGained
       jTextFieldCodigoEquipo.setText("");
    }//GEN-LAST:event_jTextFieldCodigoEquipoFocusGained

    private void jTextFieldCodigoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoEquipoActionPerformed

    private void jTextFieldCodigoEquipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoEquipoFocusLost
       if (jTextFieldCodigoEquipo.getText().equals("")){
           jTextFieldCodigoEquipo.setText("Código Equipo");
       }
    }//GEN-LAST:event_jTextFieldCodigoEquipoFocusLost

    private void jTextFieldUbicacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbicacionFocusGained
         jTextFieldUbicacion.setText("");      // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUbicacionFocusGained

    private void jTextFieldUbicacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbicacionFocusLost
        if (jTextFieldUbicacion.getText().equals("")){
           jTextFieldUbicacion.setText("Ubicación");
       }
    }//GEN-LAST:event_jTextFieldUbicacionFocusLost

    private void jTextFieldPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecioFocusGained
        jTextFieldPrecio.setText("");        
    }//GEN-LAST:event_jTextFieldPrecioFocusGained

    private void jTextFieldPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecioFocusLost
        if (jTextFieldPrecio.getText().equals("")) {
            jTextFieldPrecio.setText("Precio");
        }
    }//GEN-LAST:event_jTextFieldPrecioFocusLost

    private void jRadioButtonPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPcActionPerformed

    private void jTextFieldTipoPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoPCActionPerformed

    private void jTextFieldSisOperativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSisOperativoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSisOperativoMouseClicked

    private void jTextFieldSisOperativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSisOperativoFocusGained
            jTextFieldSisOperativo.setText("");
    }//GEN-LAST:event_jTextFieldSisOperativoFocusGained

    private void jTextFieldSisOperativoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSisOperativoFocusLost
        if (jTextFieldSisOperativo.getText().equals("")) {
            jTextFieldSisOperativo.setText("Sistema Operativo");
        }
    }//GEN-LAST:event_jTextFieldSisOperativoFocusLost

    private void jTextFieldTipoPCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTipoPCFocusGained
        jTextFieldTipoPC.setText("");
    }//GEN-LAST:event_jTextFieldTipoPCFocusGained

    private void jTextFieldTipoPCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTipoPCFocusLost
        if (jTextFieldTipoPC.getText().equals("")) {
            jTextFieldTipoPC.setText("Tipo PC");
        }
    }//GEN-LAST:event_jTextFieldTipoPCFocusLost

    private void jTextFieldYearCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldYearCompraFocusGained
        jTextFieldYearCompra.setText("");
    }//GEN-LAST:event_jTextFieldYearCompraFocusGained

    private void jTextFieldYearCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldYearCompraFocusLost
        if (jTextFieldYearCompra.getText().equals("")) {
            jTextFieldYearCompra.setText("Año Compra Servidor");
        }
    }//GEN-LAST:event_jTextFieldYearCompraFocusLost

    private void jTextFieldTipoImpresoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTipoImpresoraFocusGained
        jTextFieldTipoImpresora.setText("");
    }//GEN-LAST:event_jTextFieldTipoImpresoraFocusGained

    private void jTextFieldTipoImpresoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTipoImpresoraFocusLost
        if (jTextFieldTipoImpresora.getText().equals("")) {
            jTextFieldTipoImpresora.setText("Tipo Impresora");
        }
    }//GEN-LAST:event_jTextFieldTipoImpresoraFocusLost

    private void jRadioButtonPcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonPcMouseClicked
        if (jRadioButtonPc.isSelected()) {
            jTextFieldSisOperativo.setVisible(true);
            jTextFieldTipoPC.setVisible(true);
            jTextFieldYearCompra.setVisible(false);
            jTextFieldTipoImpresora.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButtonPcMouseClicked

    private void jRadioButtonServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonServidorMouseClicked
        if (jRadioButtonServidor.isSelected()) {
            jTextFieldSisOperativo.setVisible(true);
            jTextFieldTipoPC.setVisible(false);
            jTextFieldYearCompra.setVisible(true);
            jTextFieldTipoImpresora.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButtonServidorMouseClicked

    private void jRadioButtonImpresoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonImpresoraMouseClicked
        if (jRadioButtonImpresora.isSelected()) {
            jTextFieldSisOperativo.setVisible(false);
            jTextFieldTipoPC.setVisible(false);
            jTextFieldYearCompra.setVisible(false);
            jTextFieldTipoImpresora.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonImpresoraMouseClicked

    private void jButtonVerEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerEquiposActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private Controlador controlador; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAñadirEquipo;
    private javax.swing.JButton jButtonCargarEquipos;
    private javax.swing.JButton jButtonVerEquipos;
    private javax.swing.JCheckBox jCheckBoxProtegido;
    private javax.swing.JLabel jLabelFormulario;
    private javax.swing.JRadioButton jRadioButtonImpresora;
    private javax.swing.JRadioButton jRadioButtonPc;
    private javax.swing.JRadioButton jRadioButtonServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCodigoEquipo;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldSisOperativo;
    private javax.swing.JTextField jTextFieldTipoImpresora;
    private javax.swing.JTextField jTextFieldTipoPC;
    private javax.swing.JTextField jTextFieldUbicacion;
    private javax.swing.JTextField jTextFieldYearCompra;
    // End of variables declaration//GEN-END:variables
}
